keep: ""
APIToken: "1"
BotName: "1"
probability: 2
dhreplystart: (由WeLM回答)
lxdhreplystart: (由WeLM回答(连续对话))
twreplystart: (由WeLM提问)
xxreplystart: (由WeLM续写)
ydljreplystart: (由WeLM阅读理解)
model: xl
max_tokens: 256
temperature: 0.85
top_p: 0.95
top_k: 50
n: 2
stop: "\n"
twstop: 。
dhcmdstart: welm
lxdhcmdstart: lxdh
twcmdstart: 提问
xxcmdstart: 续写
ydlicmdstart: 阅读理解
